// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: bookmark-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bookmark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Bookmark) Reset() {
	*x = Bookmark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookmark) ProtoMessage() {}

func (x *Bookmark) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookmark.ProtoReflect.Descriptor instead.
func (*Bookmark) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{0}
}

func (x *Bookmark) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bookmark) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateBookmarkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api      string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Bookmark *Bookmark `protobuf:"bytes,2,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
}

func (x *CreateBookmarkReq) Reset() {
	*x = CreateBookmarkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookmarkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkReq) ProtoMessage() {}

func (x *CreateBookmarkReq) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkReq.ProtoReflect.Descriptor instead.
func (*CreateBookmarkReq) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookmarkReq) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *CreateBookmarkReq) GetBookmark() *Bookmark {
	if x != nil {
		return x.Bookmark
	}
	return nil
}

type CreateBookmarkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api      string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Bookmark *Bookmark `protobuf:"bytes,2,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
}

func (x *CreateBookmarkRes) Reset() {
	*x = CreateBookmarkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBookmarkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkRes) ProtoMessage() {}

func (x *CreateBookmarkRes) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkRes.ProtoReflect.Descriptor instead.
func (*CreateBookmarkRes) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookmarkRes) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *CreateBookmarkRes) GetBookmark() *Bookmark {
	if x != nil {
		return x.Bookmark
	}
	return nil
}

type ReadBookmarkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api      string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Bookmark *Bookmark `protobuf:"bytes,2,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
}

func (x *ReadBookmarkReq) Reset() {
	*x = ReadBookmarkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookmarkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookmarkReq) ProtoMessage() {}

func (x *ReadBookmarkReq) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookmarkReq.ProtoReflect.Descriptor instead.
func (*ReadBookmarkReq) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadBookmarkReq) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ReadBookmarkReq) GetBookmark() *Bookmark {
	if x != nil {
		return x.Bookmark
	}
	return nil
}

type ReadBookmarkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api       string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Bookmarks []*Bookmark `protobuf:"bytes,2,rep,name=bookmarks,proto3" json:"bookmarks,omitempty"`
}

func (x *ReadBookmarkRes) Reset() {
	*x = ReadBookmarkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBookmarkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBookmarkRes) ProtoMessage() {}

func (x *ReadBookmarkRes) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBookmarkRes.ProtoReflect.Descriptor instead.
func (*ReadBookmarkRes) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadBookmarkRes) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ReadBookmarkRes) GetBookmarks() []*Bookmark {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

type DeleteBookmarkReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api      string    `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Bookmark *Bookmark `protobuf:"bytes,2,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
}

func (x *DeleteBookmarkReq) Reset() {
	*x = DeleteBookmarkReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookmarkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkReq) ProtoMessage() {}

func (x *DeleteBookmarkReq) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkReq.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkReq) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBookmarkReq) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *DeleteBookmarkReq) GetBookmark() *Bookmark {
	if x != nil {
		return x.Bookmark
	}
	return nil
}

type DeleteBookmarkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api       string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Bookmarks []*Bookmark `protobuf:"bytes,2,rep,name=bookmarks,proto3" json:"bookmarks,omitempty"`
}

func (x *DeleteBookmarkRes) Reset() {
	*x = DeleteBookmarkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBookmarkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkRes) ProtoMessage() {}

func (x *DeleteBookmarkRes) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkRes.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkRes) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBookmarkRes) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *DeleteBookmarkRes) GetBookmarks() []*Bookmark {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

type ListBookmarksReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
}

func (x *ListBookmarksReq) Reset() {
	*x = ListBookmarksReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBookmarksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksReq) ProtoMessage() {}

func (x *ListBookmarksReq) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksReq.ProtoReflect.Descriptor instead.
func (*ListBookmarksReq) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListBookmarksReq) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

type ListBookmarksRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api       string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Bookmarks []*Bookmark `protobuf:"bytes,2,rep,name=bookmarks,proto3" json:"bookmarks,omitempty"`
}

func (x *ListBookmarksRes) Reset() {
	*x = ListBookmarksRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookmark_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBookmarksRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksRes) ProtoMessage() {}

func (x *ListBookmarksRes) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksRes.ProtoReflect.Descriptor instead.
func (*ListBookmarksRes) Descriptor() ([]byte, []int) {
	return file_bookmark_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListBookmarksRes) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *ListBookmarksRes) GetBookmarks() []*Bookmark {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

var File_bookmark_service_proto protoreflect.FileDescriptor

var file_bookmark_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x2c, 0x0a, 0x08,
	0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x4f, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70,
	0x69, 0x12, 0x28, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x4f, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x70, 0x69, 0x12, 0x28, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61,
	0x72, 0x6b, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x4d, 0x0a, 0x0f,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70,
	0x69, 0x12, 0x28, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x4f, 0x0a, 0x0f, 0x52,
	0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69,
	0x12, 0x2a, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72,
	0x6b, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x22, 0x4f, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x61, 0x70, 0x69, 0x12, 0x28, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d,
	0x61, 0x72, 0x6b, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x51, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52,
	0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x70, 0x69, 0x12, 0x2a, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73,
	0x22, 0x24, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x22, 0x50, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x2a, 0x0a, 0x09,
	0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x09, 0x62,
	0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x32, 0x88, 0x02, 0x0a, 0x0f, 0x42, 0x6f, 0x6f,
	0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x15,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61,
	0x72, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0c,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x13, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65,
	0x71, 0x1a, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x6d,
	0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x6d,
	0x61, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x3b, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x12, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73,
	0x52, 0x65, 0x73, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x61, 0x71, 0x61, 0x69, 0x73, 0x68, 0x74, 0x79, 0x61, 0x71, 0x2f, 0x62, 0x6f,
	0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bookmark_service_proto_rawDescOnce sync.Once
	file_bookmark_service_proto_rawDescData = file_bookmark_service_proto_rawDesc
)

func file_bookmark_service_proto_rawDescGZIP() []byte {
	file_bookmark_service_proto_rawDescOnce.Do(func() {
		file_bookmark_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bookmark_service_proto_rawDescData)
	})
	return file_bookmark_service_proto_rawDescData
}

var file_bookmark_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bookmark_service_proto_goTypes = []interface{}{
	(*Bookmark)(nil),          // 0: v1.Bookmark
	(*CreateBookmarkReq)(nil), // 1: v1.CreateBookmarkReq
	(*CreateBookmarkRes)(nil), // 2: v1.CreateBookmarkRes
	(*ReadBookmarkReq)(nil),   // 3: v1.ReadBookmarkReq
	(*ReadBookmarkRes)(nil),   // 4: v1.ReadBookmarkRes
	(*DeleteBookmarkReq)(nil), // 5: v1.DeleteBookmarkReq
	(*DeleteBookmarkRes)(nil), // 6: v1.DeleteBookmarkRes
	(*ListBookmarksReq)(nil),  // 7: v1.ListBookmarksReq
	(*ListBookmarksRes)(nil),  // 8: v1.ListBookmarksRes
}
var file_bookmark_service_proto_depIdxs = []int32{
	0,  // 0: v1.CreateBookmarkReq.bookmark:type_name -> v1.Bookmark
	0,  // 1: v1.CreateBookmarkRes.bookmark:type_name -> v1.Bookmark
	0,  // 2: v1.ReadBookmarkReq.bookmark:type_name -> v1.Bookmark
	0,  // 3: v1.ReadBookmarkRes.bookmarks:type_name -> v1.Bookmark
	0,  // 4: v1.DeleteBookmarkReq.bookmark:type_name -> v1.Bookmark
	0,  // 5: v1.DeleteBookmarkRes.bookmarks:type_name -> v1.Bookmark
	0,  // 6: v1.ListBookmarksRes.bookmarks:type_name -> v1.Bookmark
	1,  // 7: v1.BookmarkService.CreateBookmark:input_type -> v1.CreateBookmarkReq
	3,  // 8: v1.BookmarkService.ReadBookmark:input_type -> v1.ReadBookmarkReq
	5,  // 9: v1.BookmarkService.DeleteBookmark:input_type -> v1.DeleteBookmarkReq
	7,  // 10: v1.BookmarkService.ListBookmarks:input_type -> v1.ListBookmarksReq
	2,  // 11: v1.BookmarkService.CreateBookmark:output_type -> v1.CreateBookmarkRes
	4,  // 12: v1.BookmarkService.ReadBookmark:output_type -> v1.ReadBookmarkRes
	6,  // 13: v1.BookmarkService.DeleteBookmark:output_type -> v1.DeleteBookmarkRes
	8,  // 14: v1.BookmarkService.ListBookmarks:output_type -> v1.ListBookmarksRes
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_bookmark_service_proto_init() }
func file_bookmark_service_proto_init() {
	if File_bookmark_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bookmark_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookmark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookmarkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBookmarkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookmarkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBookmarkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookmarkReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBookmarkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBookmarksReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookmark_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBookmarksRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bookmark_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookmark_service_proto_goTypes,
		DependencyIndexes: file_bookmark_service_proto_depIdxs,
		MessageInfos:      file_bookmark_service_proto_msgTypes,
	}.Build()
	File_bookmark_service_proto = out.File
	file_bookmark_service_proto_rawDesc = nil
	file_bookmark_service_proto_goTypes = nil
	file_bookmark_service_proto_depIdxs = nil
}
